apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: local-dev
build:
  local:
    push: false                # load images straight into kind
    tryImportMissing: true     # speed up by reusing local images
    concurrency: 3
    useBuildkit: true
    useDockerCLI: true
  tagPolicy:
    gitCommit: {}
  artifacts:
    - image: microservices-app/orders-service
      context: .                               # <— repo root!
      docker:
        dockerfile: services/orders-service/Dockerfile
    - image: microservices-app/inventory-service
      context: .
      docker:
        dockerfile: services/inventory-service/Dockerfile
    - image: microservices-app/payment-service
      context: .
      docker:
        dockerfile: services/payment-service/Dockerfile
manifests:
  rawYaml:
    - deploy/local/00-namespace.yaml
    - deploy/local/01-config.yaml
    - deploy/local/orders.yaml
    - deploy/local/inventory.yaml
    - deploy/local/payment.yaml
deploy:
  kubectl:
    flags:
      apply: ["--server-side", "--force-conflicts"]
portForward:
  - resourceType: service
    resourceName: orders-service
    namespace: local-dev
    port: 8080
    localPort: 8081
  - resourceType: service
    resourceName: inventory-service
    namespace: local-dev
    port: 8080
    localPort: 8082
  - resourceType: service
    resourceName: payment-service
    namespace: local-dev
    port: 8080
    localPort: 8083
