apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: local-dev
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: payment-service
  template:
    metadata:
      labels: 
        app: payment-service
    spec:
      containers:
        - name: app
          image: microservices-app/payment-service # tag injected by Skaffold
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SPRING_PROFILES_ACTIVE
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080 
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: local-dev
spec:
  selector:
    app: payment-service
  ports:
    - port: 8080
      targetPort: 8080
