server: { port: 8080 }
management.endpoints.web.exposure.include: health,info
springdoc: { api-docs.path: /v3/api-docs, swagger-ui.path: /swagger }
inventory:
  url: ${INVENTORY_URL:http://localhost:8081}
payment:
  url: ${PAYMENT_URL:http://localhost:8082}