name: dispatch-platform-cd

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment'
        default: 'prd'

jobs:
  detect-and-dispatch:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - id: detect
        run: |
          changed=$(git diff --name-only HEAD~1 HEAD | grep '^services/' || true)
          for s in orders-service inventory-service payment-service; do
            if echo "$changed" | grep -q "^services/$s/"; then
              echo "changed_$s=true" >> "$GITHUB_OUTPUT"
            fi
          done

      - name: Dispatch orders
        if: steps.detect.outputs.changed_orders-service == 'true'
        env:
          GH_TOKEN: ${{ secrets.CD_REPO_TOKEN }}
        run: |
          SHA=${GITHUB_SHA::8}
          gh api repos/lordpangan/platform-cd/dispatches \
            -f event_type='deploy-uat' \
            -f client_payload='{"service":"orders-service","tag":"sha-'$SHA'"}'

      - name: Dispatch inventory
        if: steps.detect.outputs.changed_inventory-service == 'true'
        env:
          GH_TOKEN: ${{ secrets.CD_REPO_TOKEN }}
        run: |
          SHA=${GITHUB_SHA::8}
          gh api repos/lordpangan/platform-cd/dispatches \
            -f event_type='deploy-uat' \
            -f client_payload='{"service":"inventory-service","tag":"sha-'$SHA'"}'

      - name: Dispatch payment
        if: steps.detect.outputs.changed_payment-service == 'true'
        env:
          GH_TOKEN: ${{ secrets.CD_REPO_TOKEN }}
        run: |
          SHA=${GITHUB_SHA::8}
          gh api repos/lordpangan/platform-cd/dispatches \
            -f event_type='deploy-uat' \
            -f client_payload='{"service":"payment-service","tag":"sha-'$SHA'"}'
